services:
  app:
    build: .
    container_name: express-app
    ports:
      - '3000:3000'
    environment:
      - DB_NAME=prueba_db
      - DB_USER=root
      - DB_PASSWORD=    # Set DB_PASSWORD to an empty string
      - DB_HOST=database    # Use "database" as the host to match the service name
      - DB_PORT=3306
      - PORT=3000
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    command: node index.js
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes   # Allow an empty password
      - MYSQL_ROOT_PASSWORD=             # Leave empty to allow no password for root
      - MYSQL_DATABASE=prueba_db
    ports:
      - '3306:3306'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
